# Runs clang-tidy over SOURCES in parallel batches (cmake -P script, no shell dependency).
# Inputs: CLANG_TIDY, BUILD_DIR, SOURCES (;-list)
cmake_host_system_information(RESULT _jobs QUERY NUMBER_OF_LOGICAL_CORES)
if(NOT _jobs OR _jobs LESS 1)
  set(_jobs 1)
endif()

set(_pending ${SOURCES})
list(LENGTH _pending _count)
set(_failed 0)
set(_index 0)
while(_index LESS _count)
  set(_cmds "")
  set(_batch "")
  foreach(_j RANGE 1 ${_jobs})
    if(_index LESS _count)
      list(GET _pending ${_index} _file)
      list(APPEND _cmds COMMAND "${CLANG_TIDY}" -p "${BUILD_DIR}" --quiet "${_file}")
      list(APPEND _batch "${_file}")
      math(EXPR _index "${_index} + 1")
    endif()
  endforeach()
  execute_process(${_cmds} RESULTS_VARIABLE _results)
  foreach(_r IN LISTS _results)
    if(NOT _r EQUAL 0)
      set(_failed 1)
    endif()
  endforeach()
endwhile()

if(_failed)
  message(FATAL_ERROR "clang-tidy reported findings (see output above)")
endif()
message(STATUS "clang-tidy: ${_count} files clean")
